spring:
  application:
    name: MyTestJavaSpringbootMaven
  datasource:
    url: jdbc:mysql://localhost:3306/mytestjava
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
server:
  port: 8100
  servlet:
    context-path: /mytestjavaspringbootmaven